### ISSUE TITLE
App.js Code can be refactored 

### ISSUE THREAD

**Issue by mpaccione** [BGeil/Simon-Says-Game#1]
Hi Bryan,

I'm going to be occasionally looking out for you because I do that shit for proper people.

You can refactor the click handlers by having one function and storing the selectors in an array and then using a for loop with the index to loop over ie....

You have this...

```
$(`.yellow`).on(`click`, () => {
	console.log(`The yellow button is working!`);
	game.flashButton(1);
})

$(`.red`).on(`click`, () => {
	console.log('The red button is working!');
	game.flashButton(2);
})

$(`.green`).on(`click`, () => {
	console.log('The green button is working!');
	game.flashButton(3);	
})

$(`.blue`).on(`click`, () => {
	console.log(`The blue button is working!`);
	game.flashButton(4);
})
```

But I would write it like this...

```
const colorSelectors = [ 
   $('.yellow'),
   $('.red'),
   $('.green'),
   $('.blue')
];

for (i = 0; i < colorSelectors.length; i++) {
  colorSelectors[i].on('click', function(){
     console.log(`The ${colorSelector[i].toString()} button is working!`);
     game.flashButton(i+1);
  })
}
```

You have this code here:

```
flashButton: function(n) {
		if (n === 1) {
			$(`.yellow`).addClass('flash-button')
			setTimeout(() => {
				$(`.yellow`).removeClass('flash-button')	
			}, 75)
		} else if (n === 2) {
			$(`.red`).addClass('flash-button')
			setTimeout(() => {
				$(`.red`).removeClass('flash-button')	
			}, 75)
		} else if (n === 3) {
			$(`.green`).addClass('flash-button')
			setTimeout(() => {
				$(`.green`).removeClass('flash-button')	
			}, 75)
		} else if (n === 4) {
			$(`.blue`).addClass('flash-button')
			setTimeout(() => {
				$(`.blue`).removeClass('flash-button')	
			}, 75)
		}
			
	}
```

This is super verbose and excessive. You could rewrite this with the colorSelector array which I created above as...

```
flashButton: function(n){
  colorSelectors[n+1].addClass('flash-button');
  setTimeout(function(){
     colorSelectors[n+1].removeClass('flash-button')
  }, 75)
}
```

**Comment by BGeil** [comment]
Hey Michael thanks for the help, I really do appreciate it! This project is one of many that I am doing for General Assembly. All of my instructors and potential future employers will looking at this repo. If you have any suggestions for writing DRY code I am open for advice. I would prefer it though if you could DM or text me with any future suggestions. Flagging an issue on my code implies that there is actually something broken with my code. While the code definitely has room for improvement, everything runs just fine.  I will be closing this issue, thank you.

**Comment by mpaccione** [comment]
Okay well can't DM you on github anymore, they removed that feature a long time ago... good luck in your ventures.
